ZEN-29514: Need to upgrade OpenSSL to supported version
Update the pyOpenSSL package to prevent the
`AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error
in LDAPMultiPlugin